const translations = {
    en: {
        titleTag: "CS2 Manager",
        mainTitle: "CS2 Float Manager",
        langLabel: "🌐",
        tabFloat: "Calculate Final Float",
        tabAvg: "Calculate Max Avg Float",
        floatStep1: "1. Enter 10 floats for CS2 weapons",
        calcAvgBtn: "Calculate average",
        floatStep2: "2. Enter Max/Min Cap",
        maxCapLabel: "Max Cap:",
        minCapLabel: "Min Cap:",
        calcFloatBtn: "Calculate final float",
        avgStep2: "2. Calculate Max Avg Float",
        skinSearchLabel: "Search skin:",
        skinSearchPlaceholder: "e.g. AK-47 | Redline",
        targetFloatLabel: "Target wear:",
        optFactoryNew: "Factory New (0.00 - 0.0699999…)",
        optMinimalWear: "Minimal Wear (0.07 - 0.1499999…)",
        optFieldTested: "Field-Tested (0.15 - 0.3799999…)",
        optWellWorn: "Well-Worn (0.38 - 0.4499999…)",
        optBattleScarred: "Battle-Scarred (0.45 - 1.00)",
        maxCap2Label: "Max Cap:",
        minCap2Label: "Min Cap:",
        calcMaxAvgBtn: "Calculate Max Avg Float",
        wearShort: ['FN', 'MW', 'FT', 'WW', 'BS'], // Kurzlabels für Float-Input
        wearFull: ['Factory New','Minimal Wear','Field-Tested','Well-Worn','Battle-Scarred'] // Langlabels
    },
    de: {
        titleTag: "CS2 Manager",
        mainTitle: "CS2 Float Manager",
        langLabel: "🌐",
        tabFloat: "Finalen Float berechnen",
        tabAvg: "Max. Durchschnitt berechnen",
        floatStep1: "1. Gib 10 Floats für CS2-Waffen ein",
        calcAvgBtn: "Durchschnitt berechnen",
        floatStep2: "2. Max/Min Cap eingeben",
        maxCapLabel: "Max Cap:",
        minCapLabel: "Min Cap:",
        calcFloatBtn: "Finalen Float berechnen",
        avgStep2: "2. Max. Durchschnitts-Float berechnen",
        skinSearchLabel: "Skin suchen:",
        skinSearchPlaceholder: "z.B. AK-47 | Redline",
        targetFloatLabel: "Ziel-Abnutzung:",
        optFactoryNew: "Fabrikneu (0.00 - 0.0699999…)",
        optMinimalWear: "Minimale Gebrauchsspuren (0.07 - 0.1499999…)",
        optFieldTested: "Einsatzerprobt (0.15 - 0.3799999…)",
        optWellWorn: "Abgenutzt (0.38 - 0.4499999…)",
        optBattleScarred: "Kampfspuren (0.45 - 1.00)",
        maxCap2Label: "Max Cap:",
        minCap2Label: "Min Cap:",
        calcMaxAvgBtn: "Max. Durchschnitt berechnen",
        wearShort: ['FN', 'MW', 'FT', 'WW', 'BS'], // Kurzlabels für Float-Input
        wearFull: ['Fabrikneu','Minimale Gebrauchsspuren','Einsatzerprobt','Abgenutzt','Kampfspuren'] // Langlabels
    }
};
