name: Update LOC Stats

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cloc
      run: sudo apt-get install -y cloc
      
    - name: Count lines of code
      run: |
        cloc --exclude-dir=node_modules,dist --csv --quiet . > cloc.csv
        echo "LINES=$(awk -F, '/SUM/{print $5}' cloc.csv)" >> $GITHUB_ENV
        echo "JS=$(awk -F, '/JavaScript/{print $5}' cloc.csv)" >> $GITHUB_ENV
        echo "CSS=$(awk -F, '/CSS/{print $5}' cloc.csv)" >> $GITHUB_ENV
        echo "HTML=$(awk -F, '/HTML/{print $5}' cloc.csv)" >> $GITHUB_ENV
        
    - name: Update README with stats
      run: |
        # README lesen und ersetzen
        sed -i "s/📊 **Code Statistics:**.*/📊 **Code Statistics:**/" README.md
        sed -i "/📊 **Code Statistics:**/a\\
        - **Total Lines:** $LINES\\
        - **JavaScript:** $JS\\
        - **CSS:** $CSS\\
        - **HTML:** $HTML\\
        " README.md
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "📊 Update code statistics: $LINES total lines"
        git push
